### ISSUE TITLE
local cache bypass for external data

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2946]
In an environment where CVMFS is:
*  presenting external data
*  files are read once, and not re-read
* upstream HTTP caches are fast
* local storage is small/slow
* kernel supports large fuse payloads > 128kiB (RHEL8 supports up to 2MiB)

it can be useful to have a read mode that bypasses CVMFS's local cache entirely.

Implementation notes:
* fuse_open() has existing behaviour, except for external data it does not download first chunk of object,
* fuse_read() has existing behaviour, except for reads to external data which are translated to a ranged http download to memory. No checksum validation is done (as read will not be of whole chunk).

If might be reasonable to have this pathway activate if the file is opened O_DIRECT, but it should also be configurable 
 for the whole mount, to avoid any application modification.

**Comment by HereThereBeDragons** [comment]
Is this solved by #3263 ?

**Comment by jblomer** [comment]
According to our last discussion, I understand that we are still missing a little bit of caching, to avoid multiple downloads triggered by a mismatch of the fuse request chunk size and the cvmfs object sizes.
